//@ sourceMappingURL=main.map
// Generated by CoffeeScript 1.6.1
(function() {

  $(function() {
    var WordsViewModel;
    $.ajax({
      url: './en.txt',
      success: function(result) {
        var trie, word, words, _i, _len;
        words = result.match(/[^\r\n]+/g);
        trie = new Cheat.Trie;
        for (_i = 0, _len = words.length; _i < _len; _i++) {
          word = words[_i];
          trie.append(word);
        }
        console.log(trie);
        window.trie = trie;
        $('#letters-input').removeAttr('disabled');
        return $('#letters-button').removeAttr('disabled');
      },
      async: false
    });
    WordsViewModel = (function() {

      function WordsViewModel() {}

      WordsViewModel.prototype.words = ko.observableArray([]);

      return WordsViewModel;

    })();
    window.wordsViewModel = new WordsViewModel;
    ko.applyBindings(window.wordsViewModel);
    return $('#letters-button').click(function() {
      var words;
      window.wordsViewModel.words.removeAll();
      words = window.trie.words(window.trie.group($('#letters-input').val().split('')));
      return window.wordsViewModel.words(_.shuffle(words).slice(0, 99));
    });
  });

}).call(this);
