//@ sourceMappingURL=main.map
// Generated by CoffeeScript 1.6.1
(function() {

  requirejs.config({
    paths: {
      'bootstrap': 'vendor/bootstrap',
      'jquery': 'vendor/jquery',
      'knockout': 'vendor/knockout',
      'underscore': 'vendor/underscore',
      'domReady': 'vendor/domReady',
      'text': 'vendor/text',
      'Model': 'model',
      'ViewModel': 'view-model'
    },
    shim: {
      bootstrap: {
        deps: ['jquery']
      },
      underscore: {
        exports: '_'
      }
    },
    waitSeconds: 600
  });

  require(['jquery', 'underscore', 'bootstrap', 'knockout', 'view-model', 'domReady!'], function($, _, Bootstrap, ko, ViewModel, doc) {
    var viewModel;
    viewModel = new ViewModel;
    $('#input-letters').keyup(function(event) {
      if (/[a-zA-Z]/.test(String.fromCharCode(event.keyCode))) {
        $('#input-letters').val($('#input-letters').val().toLowerCase());
      }
      return viewModel.find($('#input-letters').val());
    });
    ko.applyBindings(viewModel);
    return $('#input-letters').focus();
  });

}).call(this);
