//@ sourceMappingURL=model.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['vendor/text!../en.txt'], function(en) {
    var Model;
    Model = (function() {

      function Model() {}

      Model.find = function(letters) {
        var result, words, _i, _len, _word;
        result = [];
        words = Model.words();
        for (_i = 0, _len = words.length; _i < _len; _i++) {
          _word = words[_i];
          if (Model.word(_word, letters)) {
            result.push(_word);
          }
        }
        return result;
      };

      Model.word = function(word, letters) {
        var letter, _i, _len;
        for (_i = 0, _len = word.length; _i < _len; _i++) {
          letter = word[_i];
          if (!-1 > letters.indexOf(letter)) {
            return false;
          }
          letters = letters.replace(letter, '');
        }
        return true;
      };

      Model.words = function() {
        return en.match(/[^\r\n]+/g);
      };

      return Model;

    })();
    return Model;
  });

}).call(this);
