// Generated by CoffeeScript 2.5.1
(function() {
  define(['vendor/text!../en.txt'], function(en) {
    var Model;
    Model = class Model {
      static find(letters) {
        var _word, i, len, result, words;
        result = [];
        words = Model.words();
        for (i = 0, len = words.length; i < len; i++) {
          _word = words[i];
          if (Model.word(_word, letters)) {
            result.push(_word);
          }
        }
        return result;
      }

      static word(word, letters) {
        var i, len, letter;
        for (i = 0, len = word.length; i < len; i++) {
          letter = word[i];
          if (!-1 > letters.indexOf(letter)) {
            return false;
          }
          letters = letters.replace(letter, '');
        }
        return true;
      }

      static words() {
        return en.match(/[^\r\n]+/g);
      }

    };
    return Model;
  });

}).call(this);

//# sourceMappingURL=model.js.map
