//@ sourceMappingURL=trie.map
// Generated by CoffeeScript 1.6.1
(function() {

  LetterpressCheat.Trie = (function() {

    function Trie() {}

    Trie.prototype.children = [];

    Trie.prototype.parent = void 0;

    Trie.prototype.isRoot = function() {
      return this.parent != null;
    };

    return Trie;

  })();

}).call(this);
