//@ sourceMappingURL=view-model.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['underscore', 'knockout'], function(_, ko) {
    var ViewModel;
    ViewModel = (function() {
      var worker;

      worker = void 0;

      function ViewModel() {
        var self;
        self = this;
        this.worker = new Worker('./js/worker.js');
        this.worker.onmessage = function(event) {
          self.total(event.data.total);
          self.found(event.data.words.length);
          return self.words(event.data.words);
        };
        this.loading = ko.computed(function() {
          return self.total === '';
        });
        this.wordsString = ko.computed(function() {
          return ViewModel.filter(self.words(), self.requiredLetters()).join(', ');
        }, self);
      }

      ViewModel.prototype.total = ko.observable('');

      ViewModel.prototype.requiredLetters = ko.observable('');

      ViewModel.prototype.found = ko.observable(0);

      ViewModel.prototype.words = ko.observableArray([]);

      ViewModel.filter = function(words, letters) {
        if (letters === '') {
          return words;
        }
        return _.filter(words, function(word) {
          var intersection, uniq;
          uniq = _.uniq(letters);
          intersection = _.intersection(word, uniq);
          return intersection.length === uniq.length;
        });
      };

      ViewModel.prototype.find = function(letters) {
        return this.worker.postMessage(letters);
      };

      return ViewModel;

    })();
    return ViewModel;
  });

}).call(this);
