// Generated by CoffeeScript 2.5.1
(function() {
  importScripts('require.js');

  require({
    baseUrl: './'
  }, ['require', 'model'], function(require, Model) {
    var result;
    result = {
      total: Model.words().length,
      words: []
    };
    postMessage(result);
    return this.onmessage = function(oEvent) {
      var letters;
      letters = oEvent.data;
      result = {
        total: Model.words().length,
        words: Model.find(letters)
      };
      return postMessage(result);
    };
  });

}).call(this);

//# sourceMappingURL=worker.js.map
