//@ sourceMappingURL=trie-test.map
// Generated by CoffeeScript 1.6.1
(function() {
  var TrieTest;

  TrieTest = (function() {

    function TrieTest() {}

    return TrieTest;

  })();

}).call(this);
